apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: glb-ingress
spec:
 rules:
   - host: els.alopez.io
     http:
       paths:
       - path: /
         backend:
           serviceName: electronistore-ci
           servicePort: 80